[build]
  command = "cd react-app && npm install && npm run build"
  publish = "react-app/build"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  functionsTimeout = 60000  # 60 seconds for local development