[build]
  command = "cd react-app && npm install && npm run build"
  publish = "react-app/build"

[functions]
  directory = "functions"  # Only include if using serverless functions

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200